### ISSUE TITLE
User Auth MVP 

### ISSUE THREAD

**Issue by pb-nowa** [pb-nowa/All-Days#2]
# User Auth
## Functionality
- [ ] The main button with logo should link to `/`
- [ ] Has working demo login
- [ ] Smooth, bug free navigation
### Before Login
- [ ] The `/account' page should not display 'login/signup' if logged in.
- [ ] Going to a random route `/#/oweiniouewbrviuwebv` should redirect or display a 404 page
- [ ] Errors should display for both login and signup forms in '/account'.
- [ ] Can sign up a user
- [ ] Can sign in as a user
- [ ] Can log out a user
- [ ] Can't sign up with the same username/email
- [ ] Pressing enter after filling out the session form should use the form data, not the demo user
### After Login
- [ ] After login, `/account'  becomes the user's account page with a logout button.
- [ ] Should be able to refresh the page and still be logged in
## Style
- [ ] The site should look exactly like the actual site
- [ ] All relevant elements should have `cursor: pointer` on hover
- [ ] When errors are displayed, most elements should not move around the page (particularly input boxes)
- [ ] Remove Redux logger and all console.log()'s from production
## Seeds
- [ ] Adequate and appropriate seeds

**Comment by evhumphrey** [comment]
Looks good! Here's some feedback: 

## Styling
- [ ] Style the navbar to look like allbirds (text should be all uppercase, font is different, make sure you have the appropriate hover effects)
- [ ] Style your account page to look like this:
![Screen Shot 2019-05-02 at 2 27 09 PM](https://user-images.githubusercontent.com/6361824/57108023-73a54680-6ce6-11e9-8881-f31efc19c359.png)


## Bugs
- [ ] The errors show up over both forms; they should only show up on the appropriate form

**Comment by pb-nowa** [comment]
These have now been fixed

**Comment by evhumphrey** [comment]
Sweet, last piece of feedback: 
- [ ] Add a `cursor: pointer` for when you hover over logout`
